'use client';
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import Image from 'next/image';
import { configuredRewardTotal, funnelConfig, maxUnlockedBenefit } from '../config/funnel';
import { questions, type Question } from '../data/questions';

type Answers=Record<string,string>;
type SavedState={step:number;answers:Answers;firstName:string;phone:string;countryCode:string;unlockedValue:number;quizCompleted:boolean;leadSubmitted:boolean;utms:Record<string,string>};
const initial:SavedState={step:0,answers:{},firstName:'',phone:'',countryCode:'+52',unlockedValue:0,quizCompleted:false,leadSubmitted:false,utms:{}};
const countries=[['México','+52'],['Colombia','+57'],['Argentina','+54'],['Chile','+56'],['Perú','+51'],['Ecuador','+593'],['Bolivia','+591'],['Paraguay','+595'],['Uruguay','+598'],['Guatemala','+502'],['Costa Rica','+506'],['Panamá','+507'],['Rep. Dominicana','+1'],['El Salvador','+503'],['Honduras','+504'],['Nicaragua','+505']];
const storageKey='mercedes-bows-funnel-v2';
const sequence=['intro','q1','q2','q3','lead','q4','product','q5','expert','q6','celebration','rewards','offer'] as const;
const questionNumber=(stage:string)=>({q1:1,q2:2,q3:3,q4:4,q5:5,q6:6}[stage]||0);

function track(event:string,data:Record<string,string|number>={}){ if(typeof window==='undefined')return; window.dispatchEvent(new CustomEvent('funnel_event',{detail:{event,...data}})); const analyticsWindow=window as typeof window&{gtag?:(command:'event',eventName:string,parameters?:Record<string,string|number>)=>void}; analyticsWindow.gtag?.('event',event,data); if(process.env.NODE_ENV==='development')console.info('[analytics]',event,data); }
function money(value:number){return `${funnelConfig.currency}${Number.isInteger(value)?value:value.toFixed(2)}`}
function VisualPlaceholder({kind,label}:{kind:'expert'|'bows'|'app';label:string}){if(kind==='bows')return <div className="visual-placeholder bows real-image"><Image src={funnelConfig.images.bowKit} alt={label} fill sizes="(max-width: 520px) 90vw, 420px" /></div>;if(kind==='app')return <div className="visual-placeholder app real-image"><Image src={funnelConfig.images.appMockup} alt={label} fill sizes="150px" /></div>;return <div className="visual-placeholder expert real-image"><Image className="entry-image" src={funnelConfig.images.expertEntry} alt={label} fill sizes="(max-width: 520px) 82vw, 310px" priority/><Image className="message-image" src={funnelConfig.images.expertMessage} alt={label} fill sizes="(max-width: 520px) 82vw, 310px" /></div>}
function ProgressBar({value}:{value:number}){return <div className="progress-track" aria-label={`Progreso ${value}%`}><div className="progress-fill" style={{width:`${value}%`}} /></div>}
function AnimatedMoneyCounter({value,pulse}:{value:number;pulse:boolean}){const [shown,setShown]=useState(value);const previous=useRef(value);useEffect(()=>{const from=previous.current,start=performance.now(),duration=480;let frame=0;const run=(now:number)=>{const p=Math.min(1,(now-start)/duration);setShown(Math.round(from+(value-from)*(1-Math.pow(1-p,3))));if(p<1)frame=requestAnimationFrame(run);else previous.current=value};frame=requestAnimationFrame(run);return()=>cancelAnimationFrame(frame)},[value]);return <strong className={pulse?'money pulse':'money'}>{money(shown)}</strong>}
function QuizHeader({value,stage,pulse}:{value:number;stage:string;pulse:boolean}){const n=questionNumber(stage);const progress=Math.min(100,Math.round((value/maxUnlockedBenefit)*100));return <header className="reward-header"><div><span>Ya desbloqueaste</span><AnimatedMoneyCounter value={value} pulse={pulse}/></div><div className="surprise">🎁 Premio sorpresa</div><p>{n?`PREGUNTA ${n} DE 6`:'TU PROGRESO'}</p><ProgressBar value={progress}/><small>No es dinero en efectivo. Es un beneficio especial.</small></header>}
function RewardToast({amount,final}:{amount:number;final:boolean}){return <div className="reward-toast" role="status" aria-live="assertive"><span>{final?'🎊':'🎉'}</span><div><b>{final?'¡Felicidades!':`¡Ganaste ${money(amount)}!`}</b><small>{final?'Desbloqueaste el beneficio máximo.':'Nuevo beneficio desbloqueado'}</small></div></div>}
function PrimaryButton({children,onClick,type='button',disabled=false}:{children:React.ReactNode;onClick?:()=>void;type?:'button'|'submit';disabled?:boolean}){return <button className="primary-button" type={type} onClick={onClick} disabled={disabled}>{children}</button>}
function QuizQuestion({question,name,selected,disabled,onAnswer}:{question:Question;name:string;selected?:string;disabled:boolean;onAnswer:(id:string)=>void}){const num=questions.findIndex(q=>q.id===question.id)+1;return <div className="screen question-screen"><p className="eyebrow">PREGUNTA {num} DE 6</p><h1>{question.prompt.replace('{name}',name||'Amiga')}</h1>{question.helper&&<p className="helper">{question.helper}</p>}<div className="answers">{question.options.map(o=><button disabled={disabled} className={`answer-card ${selected===o.id?'selected':''}`} key={o.id} onClick={()=>onAnswer(o.id)}><span>{o.id}</span>{o.label}<b>›</b></button>)}</div><p className="reward-hint">Elige una opción para avanzar y desbloquear tu beneficio.</p></div>}
function LeadCapture({state,disabled,onSubmit}:{state:SavedState;disabled:boolean;onSubmit:(name:string,phone:string,code:string)=>void}){const [name,setName]=useState(state.firstName),[phone,setPhone]=useState(state.phone),[code,setCode]=useState(state.countryCode),[consent,setConsent]=useState(false),[error,setError]=useState('');useEffect(()=>track('lead_form_viewed',{currentStep:4,unlockedValue:state.unlockedValue}),[]);function submit(e:FormEvent){e.preventDefault();if(name.trim().length<2||phone.replace(/\D/g,'').length<7||!consent){setError('Completa tus datos y acepta la autorización para continuar.');return}setError('');onSubmit(name.trim().split(/\s+/)[0],phone.replace(/[^\d\s-]/g,''),code)}return <form className="screen lead-screen" onSubmit={submit}><div className="celebrate-icon">🎉</div><p className="eyebrow">¡YA DESBLOQUEASTE {money(state.unlockedValue)}!</p><h1>Mercedes quiere preparar tu resultado para ti</h1><p className="lead">Cuéntanos cómo llamarte antes de continuar.</p><label>Tu nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ej.: María Fernanda" autoComplete="given-name" /></label><label>Tu WhatsApp<div className="phone-row"><select value={code} onChange={e=>setCode(e.target.value)} aria-label="Código de país">{countries.map(([c,d])=><option key={c} value={d}>{c} {d}</option>)}</select><input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="999 999 999" autoComplete="tel" /></div></label><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Acepto recibir información relacionada con mi resultado y esta oferta.</span></label>{error&&<p className="form-error" role="alert">{error}</p>}<PrimaryButton type="submit" disabled={disabled}>GUARDAR Y CONTINUAR +US$20 →</PrimaryButton></form>}
function InfoScreen({kind,onContinue}:{kind:'product'|'expert';onContinue:()=>void}){const product=kind==='product';return <div className="screen info-screen"><VisualPlaceholder kind={product?'bows':'expert'} label={product?'Kit de lazos premium':'Foto de Mercedes'}/>{product?<><h1>Algo pequeño puede convertirse en algo mucho más grande 🎀</h1><p className="lead">Aprende a crear modelos bonitos, preparar kits y presentar tus lazos de una forma mucho más atractiva.</p></>:<><p className="tag">UN MENSAJE DE MERCEDES</p><h1>Empieza con sencillez y avanza pieza por pieza</h1><p className="lead">No necesitas comenzar con cientos de modelos. Puedes empezar aprendiendo algunos lazos, mejorando cada pieza y entendiendo cómo presentarlos de una manera atractiva.</p></>}<PrimaryButton onClick={onContinue}>CONTINUAR →</PrimaryButton></div>}
function UnlockedRewards({name,onContinue}:{name:string;onContinue:()=>void}){return <div className="screen rewards-screen"><div className="celebrate-icon">🎉</div><h1>¡Listo, {name}! Has desbloqueado todos tus regalos</h1><p className="lead">Mercedes preparó estos recursos para ayudarte a comenzar paso a paso.</p><div className="bonus-list">{funnelConfig.bonuses.map((b,i)=><div className="bonus-card" key={b.title}><span>{i+1}</span><b>{b.title}</b><strong>{money(b.value)}</strong></div>)}</div><div className="total-card"><span>TOTAL DESBLOQUEADO</span><strong>{money(configuredRewardTotal)}</strong><small>Beneficios y bonos asociados a la oferta.</small></div><PrimaryButton onClick={onContinue}>VER MI BENEFICIO ESPECIAL →</PrimaryButton></div>}
function OfferCard({name,utms}:{name:string;utms:Record<string,string>}){
  const [showExitOffer,setShowExitOffer]=useState(false);const exitOfferSeenKey='lazos-exit-offer-seen-v1';
  function openCheckout(urlString:string,event:string){track(event,{unlockedValue:maxUnlockedBenefit});const url=new URL(urlString);Object.entries(utms).forEach(([k,v])=>url.searchParams.set(k,v));window.location.href=url.toString()}
  function revealExitOffer(){if(sessionStorage.getItem(exitOfferSeenKey))return;sessionStorage.setItem(exitOfferSeenKey,'1');setShowExitOffer(true);track('exit_offer_viewed',{offerPrice:funnelConfig.exitOfferPrice})}
  useEffect(()=>{track('offer_viewed',{unlockedValue:maxUnlockedBenefit});const onMouseLeave=(event:MouseEvent)=>{if(event.clientY<=0)revealExitOffer()};const onPopState=()=>{revealExitOffer();history.pushState({exitOfferGuard:true},'',location.href)};document.addEventListener('mouseleave',onMouseLeave);history.pushState({exitOfferGuard:true},'',location.href);window.addEventListener('popstate',onPopState);return()=>{document.removeEventListener('mouseleave',onMouseLeave);window.removeEventListener('popstate',onPopState)}},[]);
  return <><div className="screen offer-screen"><p className="eyebrow">TU BENEFICIO ESPECIAL</p><h1>🎉 ¡Felicidades, {name}!</h1><p className="lead">Llegaste hasta el final y desbloqueaste tu beneficio especial.</p><div className="price-card"><div><span>PRECIO DE REFERENCIA</span><s>{money(funnelConfig.fullPrice)}</s></div><div><span>BENEFICIO DESBLOQUEADO</span><b>−{money(maxUnlockedBenefit)}</b></div><hr/><p>TU ACCESO HOY</p><strong>{money(funnelConfig.finalPrice)}</strong></div><h2>Todo lo que vas a recibir</h2><div className="app-feature"><VisualPlaceholder kind="app" label="Vista previa del aplicativo"/><ul>{funnelConfig.offerItems.map(item=><li key={item}>✓ <span>{item}</span></li>)}</ul></div><PrimaryButton onClick={()=>openCheckout(funnelConfig.checkoutUrl,'checkout_clicked')}>QUIERO MI ACCESO →</PrimaryButton><small className="honest-note">Acceso inmediato después de confirmar el pago.</small></div>{showExitOffer&&<div className="exit-offer-backdrop" role="dialog" aria-modal="true" aria-labelledby="exit-offer-title"><div className="exit-offer-modal"><button className="exit-offer-close" aria-label="Cerrar" onClick={()=>setShowExitOffer(false)}>×</button><div className="exit-offer-icon">🎁</div><p className="eyebrow">ÚLTIMA OPORTUNIDAD</p><h2 id="exit-offer-title">¡Espera, {name}! No te vayas todavía</h2><p>Mercedes liberó un descuento adicional para que puedas comenzar hoy.</p><div className="exit-offer-price"><span>De <s>{money(funnelConfig.finalPrice)}</s> por solo</span><strong>{money(funnelConfig.exitOfferPrice)}</strong><small>Pago único · acceso inmediato</small></div><PrimaryButton onClick={()=>openCheckout(funnelConfig.exitOfferCheckoutUrl,'exit_offer_clicked')}>SÍ, QUIERO MI DESCUENTO →</PrimaryButton><button className="exit-offer-decline" onClick={()=>setShowExitOffer(false)}>No, gracias. Continuar sin el descuento.</button></div></div>}</>}

export default function Home(){
  const [state,setState]=useState<SavedState>(initial),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[toast,setToast]=useState<{amount:number;final:boolean}|null>(null),[pulse,setPulse]=useState(false);
  const stage=sequence[state.step]||'intro'; const question=questions.find(q=>q.id===stage); const progressState=useMemo(()=>state,[state]);
  useEffect(()=>{const params=new URLSearchParams(location.search),utms:Record<string,string>={};['utm_source','utm_medium','utm_campaign','utm_content','utm_term','fbclid'].forEach(k=>{const v=params.get(k);if(v)utms[k]=v});try{const saved=localStorage.getItem(storageKey);if(saved)setState({...initial,...JSON.parse(saved),utms:{...JSON.parse(saved).utms,...utms}});else setState(s=>({...s,utms}))}catch{}setReady(true);track('page_view')},[]);
  useEffect(()=>{if(ready)localStorage.setItem(storageKey,JSON.stringify(state))},[state,ready]);
  function resetQuiz(){localStorage.removeItem(storageKey);setState(initial);setToast(null);setBusy(false)}
  function advance(){setState(s=>({...s,step:s.step+1}))}
  function reward(id:string,answer:string,amount:number){if(busy)return;setBusy(true);setState(s=>({...s,answers:{...s.answers,[id]:answer}}));setTimeout(()=>{setState(s=>({...s,unlockedValue:s.unlockedValue+amount}));setToast({amount,final:id==='q6'});setPulse(true);track(`quiz_question_${id.slice(1)}`,{currentStep:Number(id.slice(1)),unlockedValue:state.unlockedValue+amount,answerId:answer});setTimeout(()=>{setToast(null);setPulse(false);setBusy(false);setState(s=>({...s,step:s.step+1,quizCompleted:id==='q6'||s.quizCompleted}));if(id==='q6')track('quiz_completed',{unlockedValue:maxUnlockedBenefit})},funnelConfig.rewardDurationMs)},250)}
  function submitLead(name:string,phone:string,code:string){if(busy)return;setBusy(true);setState(s=>({...s,firstName:name,phone,countryCode:code,leadSubmitted:true}));setTimeout(()=>{setState(s=>({...s,unlockedValue:s.unlockedValue+funnelConfig.increments.lead}));setToast({amount:funnelConfig.increments.lead,final:false});setPulse(true);track('lead_submitted',{currentStep:4,unlockedValue:80});setTimeout(()=>{setToast(null);setPulse(false);setBusy(false);advance()},funnelConfig.rewardDurationMs)},250)}
  if(!ready)return <main className="loading">Preparando tu experiencia…</main>;
  return <main className="site-shell"><section className="phone-frame">{stage!=='intro'&&<QuizHeader value={state.unlockedValue} stage={stage} pulse={pulse}/>} {toast&&<RewardToast amount={toast.amount} final={toast.final}/>}<div className="stage" key={stage}>
    {stage==='intro'&&<div className="screen intro-screen"><div className="ribbon-mark">🎀</div><VisualPlaceholder kind="expert" label="Foto de Mercedes"/><p className="eyebrow">¡Hola, soy Mercedes! 🎀</p><h1>Responde 6 preguntitas y desbloquea tu beneficio especial</h1><p className="lead">Cada respuesta te acercará a una oportunidad especial para comenzar a crear hermosos lazos desde casa.</p><div className="mini-reward"><span>Ya desbloqueaste</span><strong>US$0</strong><small>🎁 Premio sorpresa</small></div><PrimaryButton onClick={()=>{track('quiz_started');advance()}}>COMENZAR AHORA →</PrimaryButton><p className="microcopy">Toma menos de 2 minutos.</p></div>}
    {question&&<QuizQuestion question={question} name={state.firstName} selected={state.answers[question.id]} disabled={busy} onAnswer={id=>reward(question.id,id,funnelConfig.increments[question.id])}/>} {stage==='lead'&&<LeadCapture state={progressState} disabled={busy} onSubmit={submitLead}/>} {stage==='product'&&<InfoScreen kind="product" onContinue={advance}/>} {stage==='expert'&&<InfoScreen kind="expert" onContinue={advance}/>} {stage==='celebration'&&<div className="screen final-unlock"><div className="celebrate-icon">🎊</div><p className="eyebrow">TODO DESBLOQUEADO</p><h1>Desbloqueaste el beneficio máximo.</h1><strong>{money(maxUnlockedBenefit)}</strong><p>Tu camino personalizado está listo.</p><PrimaryButton onClick={()=>{track('rewards_viewed',{unlockedValue:maxUnlockedBenefit});advance()}}>VER MIS REGALOS →</PrimaryButton></div>} {stage==='rewards'&&<UnlockedRewards name={state.firstName||'amiga'} onContinue={advance}/>} {stage==='offer'&&<OfferCard name={state.firstName||'amiga'} utms={state.utms}/>}</div>{process.env.NODE_ENV==='development'&&<button className="reset" onClick={resetQuiz}>Reset Quiz</button>}</section></main>
}
